package com.scrim.lolscrim.global.error;

import org.springframework.http.HttpStatus;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

	VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
	MALFORMED_REQUEST(HttpStatus.BAD_REQUEST),
	AUTH_REQUIRED(HttpStatus.UNAUTHORIZED),
	AUTH_INVALID(HttpStatus.UNAUTHORIZED),
	ACCESS_DENIED(HttpStatus.FORBIDDEN),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND),
	ROOM_NOT_FOUND(HttpStatus.NOT_FOUND),
	INVITATION_NOT_FOUND(HttpStatus.NOT_FOUND),
	GUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
	ROOM_ACCESS_DENIED(HttpStatus.FORBIDDEN),
	ROOM_MANAGEMENT_DENIED(HttpStatus.FORBIDDEN),
	INVITATION_ACCESS_DENIED(HttpStatus.FORBIDDEN),
	INVITATION_NOT_PENDING(HttpStatus.CONFLICT),
	INVITATION_EXPIRED(HttpStatus.CONFLICT),
	OPPONENT_CAPTAIN_ALREADY_ASSIGNED(HttpStatus.CONFLICT),
	DUPLICATE_PENDING_INVITATION(HttpStatus.CONFLICT),
	GUEST_ADMISSION_DISABLED(HttpStatus.FORBIDDEN),
	GUEST_ENTRY_PASSWORD_INVALID(HttpStatus.FORBIDDEN),
	PLAYER_NOT_FOUND(HttpStatus.NOT_FOUND),
	PLAYER_ALREADY_EXISTS(HttpStatus.CONFLICT),
	RIOT_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND),
	RIOT_API_KEY_MISSING(HttpStatus.SERVICE_UNAVAILABLE),
	RIOT_API_AUTH_FAILED(HttpStatus.SERVICE_UNAVAILABLE),
	RIOT_API_RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
	RIOT_API_UNAVAILABLE(HttpStatus.BAD_GATEWAY),
	MATCH_NOT_FOUND(HttpStatus.NOT_FOUND),
	MATCH_START_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
	MATCH_START_REQUEST_PENDING(HttpStatus.CONFLICT),
	MATCH_START_REQUEST_NOT_PENDING(HttpStatus.CONFLICT),
	MATCH_START_REVIEW_DENIED(HttpStatus.FORBIDDEN),
	MATCH_CREATION_DENIED(HttpStatus.CONFLICT),
	MATCH_ACTIVE_EXISTS(HttpStatus.CONFLICT),
	MATCH_RESULT_INVALID_STATE(HttpStatus.CONFLICT),
	MATCH_RESULT_REVIEW_DENIED(HttpStatus.FORBIDDEN),
	DRAFT_NOT_FOUND(HttpStatus.NOT_FOUND),
	DRAFT_INVALID_STATE(HttpStatus.CONFLICT),
	DRAFT_ACCESS_DENIED(HttpStatus.FORBIDDEN),
	DRAFT_STEP_MISMATCH(HttpStatus.CONFLICT),
	DRAFT_VERSION_CONFLICT(HttpStatus.CONFLICT),
	DRAFT_CHAMPION_INVALID(HttpStatus.BAD_REQUEST),
	DRAFT_CHAMPION_UNAVAILABLE(HttpStatus.CONFLICT),
	DRAFT_PLAYER_INVALID(HttpStatus.BAD_REQUEST),
	DRAFT_ASSIGNMENT_INVALID(HttpStatus.CONFLICT),
	DRAFT_ASSIGNMENT_CONFIRMED(HttpStatus.CONFLICT),
	SESSION_FINISH_DENIED(HttpStatus.CONFLICT),
	SESSION_NOT_FOUND(HttpStatus.NOT_FOUND),
	SESSION_ACCESS_DENIED(HttpStatus.FORBIDDEN),
	SESSION_CREATION_DENIED(HttpStatus.FORBIDDEN),
	SESSION_REVIEW_DENIED(HttpStatus.FORBIDDEN),
	SESSION_ACTIVE_EXISTS(HttpStatus.CONFLICT),
	SESSION_INVALID_ROSTER(HttpStatus.BAD_REQUEST),
	SESSION_NOT_PROPOSED(HttpStatus.CONFLICT),
	DATA_CONFLICT(HttpStatus.CONFLICT);

	private final HttpStatus status;

	public static ErrorCode from(HttpStatus status) {
		return switch (status) {
			case BAD_REQUEST -> VALIDATION_ERROR;
			case UNAUTHORIZED -> AUTH_REQUIRED;
			case FORBIDDEN -> ACCESS_DENIED;
			case NOT_FOUND -> ROOM_NOT_FOUND;
			case CONFLICT -> DATA_CONFLICT;
			default -> DATA_CONFLICT;
		};
	}
}
